name: Merge Develop to Main

on:
  pull_request:
    branches:
      - main
    types:  [opened, synchronize, reopened]

jobs:
  check-pr: 
    if: github.base_ref == 'main' && github.head_ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show working directory and files
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          ls -la */  # list subfolders

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies if requirements.txt exists
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            echo "Found requirements.txt, installing dependencies..."
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping installation."
          fi

      - name: Run tests
        run: |
          python manage.py test

      - name: Display PR info
        run: |
          echo "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          echo "From branch: ${{ github.head_ref }}"
          echo "To branch: ${{ github.base_ref }}"